# Generated by Django 3.2.11 on 2022-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_recipe_app', '0005_rename_user_recipe_created_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='recipe_cook_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='directions',
            new_name='recipe_ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='recipe_instructions',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_servings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
