# Generated by Django 3.2.11 on 2022-01-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_recipe_app', '0006_auto_20220122_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked_by_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_recipes', to='user_recipe_app.user'),
            preserve_default=False,
        ),
    ]
