# Generated by Django 3.2.11 on 2022-01-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_recipe_app', '0007_auto_20220127_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='liked_by_user',
        ),
    ]
