# Generated by Django 3.2.11 on 2022-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_recipe_app', '0008_remove_recipe_liked_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_recipes',
            field=models.ManyToManyField(related_name='liked_recipes', to='user_recipe_app.Recipe'),
        ),
    ]
